-
  name: Chris Fritz
  bio: I dig helping people learn - and coding things that help people learn. My favorite way of getting to know someone is over a warm cup, so <a href="mailto:chrisvfritz@gmail.com">shoot me an email</a> and you can tell me about <em>your</em> passions.
  tech: A lot of stuff - I like to play! I also love meeting other developers, so if there's something specific you'd like help with, I almost certainly know someone who could help if I can't.
  contact_methods:
    -
      type: GitHub
      body: chrisvfritz
    -
      type: Slack
      body: chrisvfritz
    -
      type: Email
      body: chrisvfritz@gmail.com
  roles:
    - Admin
    - Leader
    - Founder
    - Mentor
-
  name: Jesse Flores
  bio: I'm a startup junkie and tech enthusiast. The founder of StartupLansing, the non-profit that educates, connects, and celebrates entrepreneurship in mid-Michigan. With Chris, I helped found several tech meetups and launch the Code Lab. My most recent project is founding SuperWebPros, which is eliminating the hassle of building and maintaining websites for small business owners.
  tech: Ruby, HTML, CSS
  contact_methods:
    -
      type: GitHub
      body: jflores1
    -
      type: Twitter
      body: jflores1c
    -
      type: LinkedIn
      body: jafloresjr
  roles:
    - Founder
    - Leader
-
  name: Nick Rutowski
  bio: I've been working in tech since my freshman year at MSU in 2011. I got my start in professional development business intelligence applications at MSU's NSCL, since then I have had 2 internships with Epic Health Systems and completed numerous freelance jobs. I joined Code Lab as a mentor because I believe an education in software development is an incredible tool for any career. Helping students be successful is my number one priority, I'm always happy to chat about how I can help!
  tech: Python, C#, Html, JS, CSS, Rails, Node.js, UI/UX, PHP, C++, C
  contact_methods:
    -
      type: GitHub
      body: badsauce
    -
      type: Twitter
      body: badsauce
    -
      type: Email
      body: NickRutowski@gmail.com
  roles:
    - Leader
    - Mentor
-
  name: Erik Gillespie
  bio: I'm a professional juggler of coding, board gaming, writing, parenting, and businessing. The coding and businessing happens at <a href="http://technicalrex.com/" target="_blank">Technical Rex</a>, board gaming with anyone who says yes, writing on <a href="http://geekandsundry.com/author/erikgillespie/" target="_blank">Geek & Sundry</a>, and evidence of parenting can be found on my <a href="http://gillespieproject.com/" target="_blank">blog</a>.
  tech: Java, JavaScript (client- and server-side), SQL, shell scripting (including just getting around the terminal). More abstract things such as HTTP and REST. Not-coding-but-handy-for-coders things like Inkscape and Gimp, agile concepts, unit testing, and application security.
  contact_methods:
    -
      type: GitHub
      body: egillespie
    -
      type: Email
      body: erik.gillespie@gmail.com
    -
      type: Stack Overflow
      body: erik-gillespie
      url: http://stackoverflow.com/users/1696044/erik-gillespie/
    -
      type: LinkedIn
      body: eriklgillespie
    -
      type: Twitter
      body: eriklgillespie
    -
      type: Blog
      body: The Gillespie Project
      url: http://gillespieproject.com/
    -
      type: Business
      body: Technical Rex
      url: http://technicalrex.com/
  roles:
    - Mentor
-
  name: Kiera Wheatley
  bio: Hi! My name is Kiera Wheatley and I'm a Computer Science major at Michigan State University. I will be graduating in the Spring. I am pursuing a career in software development. I love video games and steak.
  tech: Beyond the languages we use for web development, I could also mentor C++, C, and C# confidently.
  contact_methods:
    -
      type: GitHub
      body: kieraw
    -
      type: LinkedIn
      body: kiera-wheatley
  roles:
    - Mentor
-
  name: Nicole Lawrence
  bio: I'm a senior at Michigan State University currently majoring in Computer Science and Engineering with a cognate in Media and Information. I am the current webmaster of MSU's Women in Computing (WIC) club. I got into computer science in high school and haven't looked back. I like how you can turn seemingly meaningless letters and numbers into something wonderful; whether it is a website or a mobile app. The list of possibilities is endless!
  tech: HTML5, CSS, JS, SCSS, PHP, and Unix terminal commands.
  contact_methods:
    -
      type: GitHub
      body: icy-wolf
    -
      type: Email
      body: nicole.lawrence93@gmail.com
  roles:
    - Mentor
-
  name: Stuart Pearman
  bio: Hi, I'm Stuart! I haven't been coding for long, a little more than two years, but what I've discovered is that you can do a lot with a little knowledge. Coding has become a passion of mine, but learning new things and sharing them with others is really what I love to do most. As someone who has too many hobbies to count, coding has complemented my life ways I never could have expected, and many of the positive opportunities I've had in the past few years would have never come to me had I not developed this wonderful new skill. I hope to continue to learn and to grow, creating new experiences for myself and others for many years to come.
  tech: Design and animation, HTML, CSS, JavaScript and jQuery, Git and GitHub, and video game development with JS Canvas or Unity.
  contact_methods:
    -
      type: GitHub
      body: stuartpearman
    -
      type: Email
      body: swpearman@gmail.com
  roles:
    - Mentor
