# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e743be925017a104d7e8d3ffa7a929259dee80d8eae8b30e62a0013572267ccaebd2ffd74820012f509e9171de4eb92b84194fde3e9f4d4e1fee47264ed414b
  :omniauth: &development_omniauth
    :github:
      :id: 571930b8726dcdddfae7
      :secret: ccd156a9d8645b31ac3be0820cbd287fcc06c759
  :stripe: &development_stripe
    :key:
      :publishable: pk_test_L9lIrgSlg4injhSVP9Vjbcl0
      :secret: sk_test_DHUDz8wyzjryyRLFCFyFZ7Yw
    :webhook_hash: a4456df09344c0ceaef597009a370b539f893761

test:
  secret_key_base: 5d3b61ce6113b7b0cc0142652bc6a8d040ed20be4e984bf99f99a3674f88a46951fbb79558d5b21e62b635b9131c3b25316b1e18be36f2970d9332cab81e6bc3
  :omniauth: *development_omniauth
  :stripe: *development_stripe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  :omniauth:
    :github:
      :id: <%= ENV["OMNIAUTH_GITHUB_KEY"] %>
      :secret: <%= ENV["OMNIAUTH_GITHUB_SECRET"] %>
  :stripe:
    :key:
      :publishable: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
      :secret: <%= ENV["STRIPE_SECRET_KEY"] %>
    :webhook_hash: <%= ENV["STRIPE_WEBHOOK_HASH"] %>
